# Rename this file to config.yml and change the values below

aspace_base_uri: # Base URI for the ArchivesSpace instance backend; e.g., http://archivesspace.example.org:8089
aspace_password: # Admin password for the ArchivesSpace instance
aspace_repo_id: # ID of the repository that contains the digital objects
